# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_start_date', models.DateTimeField()),
                ('project_end_date', models.DateTimeField()),
                ('project_url', models.CharField(blank=True, max_length=100, null=True)),
                ('project_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('project_server_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('project_client', models.CharField(max_length=100)),
                ('project_platform', models.CharField(max_length=100)),
                ('project_priority', models.IntegerField()),
                ('project_users', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
