# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_delete_addproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproject',
            name='domain',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
