# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20160122_0712'),
        ('projects', '0007_mainproject_todolistmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproject',
            name='todolistmodel',
        ),
        migrations.AddField(
            model_name='mainproject',
            name='tareas',
            field=models.ManyToManyField(blank=True, null=True, to='todolist.todolistmodel'),
        ),
    ]
