# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20160128_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainproject',
            old_name='end_date',
            new_name='due_date',
        ),
    ]
