# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todolistmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('user_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('server_assigner', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
