# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20160122_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistmodel',
            old_name='platform',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todolistmodel',
            old_name='end_date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='todolistmodel',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='todolistmodel',
            name='task',
        ),
    ]
